export const genrePrompts = [
  "Magical Realism",
  "Romantic Comedy",
  "Mystery",
  "Romance",
  "Fantasy",
  "Horror",
  "Science Fiction",
  "Dystopian",
  "Adventure",
  "Thriller/Suspense",
  "Dark academia",
  "Romantasy", //cspell:ignore Romantasy
  "Slice of Life",
];

export const perspectivePrompts = [
  "Librarian",
  "Artist",
  "Teenager",
  "Thief",
  "Scoundrel",
  "Supernatural being",
  "Animal",
  "30s/40s",
  "Older/Elderly",
  "20s",
  "Gardener",
  "Hunter",
  "Child",
  "Magician",
  "Immortal being",
  "Undead being",
  "Villain",
];

export const eraPrompts = [
  "Turn of the century",
  "Feudal Europe",
  "Contemporary",
  "Feudal East Asia",
  "1980s - 1990s",
  "Ancient city",
  "AU/High Fantasy",
  "Steampunk",
  "AU/Feudal",
  "War/post war",
]

export const tonePrompts = [
  "Best Friends",
  "Proud",
  "Revenge",
  "Angst",
  "Relief",
  "Cozy",
  "Joyful",
  "Sad",
  "Serious",
  "Unrequited love",
  "Compassionate",
  "Romantic love",
  "Excitement",
  "Found family",
  "Embarrassed",
  "Sarcasm",
  "Curious",
  "Despair",
  "Familial love",
  "Cynical",
  "Anxiety",
  "Regret",
  "Self-entitlement/self-importance",
  "Apologetic",
  "Humor",
  "Longing",
  "Playfulness",
]

export const settingPrompts = [
  "School",
  "In a vehicle",
  "Fairy forest",
  "Big city",
  "Dark + stormy night",
  "Forest",
  "Countryside",
  "Swamp",
  "Alleyway",
  "Coffee shop",
  "Market",
  "Industrial building",
  "Abandoned building",
  "Duel",
  "Battle scene",
  "Flying in the air",
  "Alien world",
  "Grave/graveyard",
  "Village",
  "Watching TV/chilling at home",
  "Ocean/beach",
  "Dream state",
  "Desert",
  "Restaurant",
  "Sewer",
  "Flower field",
  "Star ship",
  "Art studio",
  "Spain",
  "Pirate ship",
  "New Orleans/The southern US",
  "Gothic city",
  "Park",
]

export const povPrompts = [
  "1st person main character",
  "1st person limited",
  "3rd person limited",
  "3rd person omniscient",
  "2nd person omniscient",
  "2nd person limited",
];
